development:
      host: localhost
      adapter: mysql
      database: fedena
      port: 3306
      username: root
      password: carter

test: &test
      host: localhost
      adapter: mysql
      database: fedena_test
      port: 3306
      username: root
      password: carter

production:
      host: localhost
      adapter: mysql
      database: fedena
      port: 3306
      username: root
      password: carter
cucumber:
  <<: *test
